### ISSUE TITLE
Convert SSD-MobileNet model

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-openvino#5]
The [calibration instructions ](https://github.com/mlperf/inference_results_v0.5/blob/master/closed/Intel/measurements/clx_9282-2s_openvino-linux/ssd-small/Offline/intel_calibration.adoc) say to use:

```bash
$ python3  <OPENVINO_INSTALL_DIR/deployment_tools/model_optimizer/>mo.py
--input_model <path_to_model/>ssd_mobilenet_v1_quant_ft_no_zero_point_frozen_inference_graph.pb
--input_shape [1,300,300,3]
--reverse_input_channels
--tensorflow_use_custom_operations_config <OPENVINO_INSTALL_DIR/deployment_tools/model_optimizer/>extensions/front/tf/ssd_v2_support.json
--tensorflow_object_detection_api_pipeline_config <path_to_model/>pipeline.config
```

I've made `<path_to_model>` available via a variation of the SSD-MobileNet quantized model:
```
$ ck install package --tags=model,mlperf,tf,ssd-mobilenet,quantized,for.openvino
$ ls -la `ck locate env --tags=model,mlperf,tf,ssd-mobilenet,quantized,for.openvino`
total 28604
drwxrwxr-x  2 anton dvdt     4096 Apr  9 12:29 .
drwxrwxr-x 69 anton dvdt    12288 Apr  9 11:49 ..
-rw-rw-r--  1 anton dvdt     4818 Apr  9 12:29 ck-install.json
lrwxrwxrwx  1 anton dvdt       65 Apr  9 12:29 graph.pb -> ssd_mobilenet_v1_quant_ft_no_zero_point_frozen_inference_graph.pb
-rw-rw-r--  1 anton dvdt     5056 Apr  9 12:29 mscoco_label_map.pbtxt
-rw-r--r--  1 anton dvdt     4324 Apr  9 12:29 pipeline.config
-rw-rw-r--  1 anton dvdt 29243853 Mar 23 12:20 ssd_mobilenet_v1_quant_ft_no_zero_point_frozen_inference_graph.pb
```

**Comment by psyhtest** [comment]
```
$ ck virtual env --tags=lib,openvino
$ ck virtual env --tags=model,mlperf,tf,ssd-mobilenet,quantized,for.openvino
$ python3 ${CK_ENV_LIB_DLDT_IE_MO_DIR}/mo.py \
--input_model ${CK_ENV_TENSORFLOW_MODEL_TF_FROZEN_FILEPATH} \
--tensorflow_object_detection_api_pipeline_config $(dirname ${CK_ENV_TENSORFLOW_MODEL_TF_FROZEN_FILEPATH})/pipeline.config \
--input_shape [1,${CK_ENV_TENSORFLOW_MODEL_DEFAULT_HEIGHT},${CK_ENV_TENSORFLOW_MODEL_DEFAULT_WIDTH},3] \
--reverse_input_channels \
--tensorflow_use_custom_operations_config ${CK_ENV_LIB_DLDT_IE_MO_DIR}/extensions/front/tf/ssd_v2_support.json

[ WARNING ]  Use of deprecated cli option --tensorflow_use_custom_operations_config detected. Option use in the following releases will be fatal. Please use --transformations_config cli option i[19/48755]
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      /home/anton/CK_TOOLS/model-tf-mlperf-ssd-mobilenet-quantized-finetuned-for.openvino/ssd_mobilenet_v1_quant_ft_no_zero_point_frozen_inference_graph.pb
        - Path for generated IR:        /home/anton/CK_REPOS/ck-openvino/soft/lib.openvino/.
        - IR output name:       ssd_mobilenet_v1_quant_ft_no_zero_point_frozen_inference_graph
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         [1,300,300,3]
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       False
        - Reverse input channels:       True
TensorFlow specific parameters:                                                                                                                                                                    [0/48755]
        - Input model in text protobuf format:  False
        - Path to model dump for TensorBoard:   None
        - List of shared libraries with TensorFlow custom layers implementation:        None
        - Update the configuration file with input/output node names:   None
        - Use configuration file used to generate the model with Object Detection API:  /home/anton/CK_TOOLS/model-tf-mlperf-ssd-mobilenet-quantized-finetuned-for.openvino/pipeline.config
        - Operations to offload:        None
        - Patterns to offload:  None
        - Use the config file:  /home/anton/CK_TOOLS/lib-openvino-gcc-7.4.0-linux-64/dldt/model-optimizer/extensions/front/tf/ssd_v2_support.json
Model Optimizer version:        unknown version
2020-04-09 12:53:14.765174: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No s
uch file or directory; LD_LIBRARY_PATH: /home/anton/CK_TOOLS/lib-opencv-3.4.3-gcc-8.3.0-linux-64/install/lib:
2020-04-09 12:53:14.765316: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared obj
ect file: No such file or directory; LD_LIBRARY_PATH: /home/anton/CK_TOOLS/lib-opencv-3.4.3-gcc-8.3.0-linux-64/install/lib:
2020-04-09 12:53:14.765334: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing l
ibraries mentioned above are installed properly.
[ WARNING ]  
Detected not satisfied dependencies:
        tensorflow: installed: 2.1.0, required: < 2.0.0
Please install required versions of components or use install_prerequisites script
/home/anton/CK_TOOLS/lib-openvino-gcc-7.4.0-linux-64/dldt/model-optimizer/install_prerequisites/install_prerequisites_tf.sh
Note that install_prerequisites scripts may install additional components.

The Preprocessor block has been removed. Only nodes performing mean value subtraction and scaling (if applicable) are kept.

[ SUCCESS ] Generated IR version 10 model.
[ SUCCESS ] XML file: /home/anton/CK_REPOS/ck-openvino/soft/lib.openvino/./ssd_mobilenet_v1_quant_ft_no_zero_point_frozen_inference_graph.xml
[ SUCCESS ] BIN file: /home/anton/CK_REPOS/ck-openvino/soft/lib.openvino/./ssd_mobilenet_v1_quant_ft_no_zero_point_frozen_inference_graph.bin
[ SUCCESS ] Total execution time: 82.39 seconds. 
[ SUCCESS ] Memory consumed: 606 MB. 
```

Seems to be successful despite using TF 2.1. The path for generated IR was my working directory.

**Comment by psyhtest** [comment]
The same using a new package (semihardcoded for SSD-MobileNet):
```bash
$ ck install package --tags=model,openvino,ssd-mobilenet
```

**Comment by psyhtest** [comment]
```bash
$ ck cat env --tags=model,openvino
local:env:6a1149c496377f7c
#! /bin/bash
#
# --------------------[ OpenVINO-from-TF model (SSS-MobileNet) ver. 1, /home/anton/CK_REPOS/local/env/6a1149c496377f7c/env.sh ]--------------------
# Tags: 64bits,converted,converted-from-tf,dldt,host-os-linux-64,model,object-detection,openvino,ssd-mobilenet,target-os-linux-64,v1
#
# CK generated script

if [ "$1" != "1" ]; then if [ "$CK_ENV_OPENVINO_MODEL_SET" == "1" ]; then return; fi; fi

# Soft UOA           = model.openvino (ca3867b1044f859b)  (model,openvino,dldt,object-detection,converted,converted-from-tf,ssd-mobilenet,host-os-linux-64,target-os-linux-64,64bits,v1)
# Host OS UOA        = linux-64 (4258b5fe54828a50)
# Target OS UOA      = linux-64 (4258b5fe54828a50)
# Target OS bits     = 64
# Tool version       = 1
# Tool split version = [1]

# Dependencies:
. /home/anton/CK_REPOS/local/env/199a3651ba18950f/env.sh
. /home/anton/CK_REPOS/local/env/fd407ea6247b0c39/env.sh
. /home/anton/CK_REPOS/local/env/744b79f7c6d12860/env.sh

export CK_ENV_OPENVINO_MODEL_BIN=/home/anton/CK_TOOLS/model-openvino-converted-from-tf-ssd-mobilenet/graph.bin
export CK_ENV_OPENVINO_MODEL_FILENAME=/home/anton/CK_TOOLS/model-openvino-converted-from-tf-ssd-mobilenet/graph.xml
export CK_ENV_OPENVINO_MODEL_MAPPING=/home/anton/CK_TOOLS/model-openvino-converted-from-tf-ssd-mobilenet/graph.mapping
export CK_ENV_OPENVINO_MODEL_ROOT=/home/anton/CK_TOOLS/model-openvino-converted-from-tf-ssd-mobilenet
export CK_ENV_OPENVINO_MODEL_XML=/home/anton/CK_TOOLS/model-openvino-converted-from-tf-ssd-mobilenet/graph.xml

export CK_ENV_OPENVINO_MODEL_SET=1
```

**Comment by psyhtest** [comment]
Note that if I uninstall the `networkx` module:
```bash
$ python3 -m pip uninstall networkx
```
the conversion fails:
```bash
...
Installing to /home/anton/CK_TOOLS/model-openvino-converted-from-tf-ssd-mobilenet

Traceback (most recent call last):
  File "/home/anton/CK_TOOLS/lib-openvino-gcc-7.4.0-linux-64/dldt/model-optimizer/mo.py", line 28, in <module>
    from mo.main import main
  File "/home/anton/CK_TOOLS/lib-openvino-gcc-7.4.0-linux-64/dldt/model-optimizer/mo/main.py", line 27, in <module>
    from extensions.back.SpecialNodesFinalization import RemoveConstOps, CreateConstNodesReplacement, RemoveOutputOps, \
  File "/home/anton/CK_TOOLS/lib-openvino-gcc-7.4.0-linux-64/dldt/model-optimizer/extensions/back/SpecialNodesFinalization.py", line 22, in <module>
    from extensions.back.pass_separator import BackFinish
  File "/home/anton/CK_TOOLS/lib-openvino-gcc-7.4.0-linux-64/dldt/model-optimizer/extensions/back/pass_separator.py", line 16, in <module>
    from mo.back.replacement import BackReplacementPattern
  File "/home/anton/CK_TOOLS/lib-openvino-gcc-7.4.0-linux-64/dldt/model-optimizer/mo/back/replacement.py", line 17, in <module>
    from mo.utils import class_registration
  File "/home/anton/CK_TOOLS/lib-openvino-gcc-7.4.0-linux-64/dldt/model-optimizer/mo/utils/class_registration.py", line 20, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
```
It's because `defusedxml` and `networkx` are _implicit_ dependencies, unlike `numpy` and `tensorflow` that are explicit. See https://github.com/ctuning/ck-openvino/issues/3.
